version: "3"
services:
  app:
    build: .
    ports:
      - 8000:8000
    tty: true
    restart: unless-stopped
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      AUTHORIZATION_URL: ${AUTHORIZATION_URL}
      TOKEN_URL: ${TOKEN_URL}
      USER_API_URL: ${USER_API_URL}
      GITHUB_API_KEY: ${GITHUB_API_KEY}
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: app
    depends_on:
      - db

  db:
    container_name: app_db
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_PASSWORD: password
      MARIADB_USER: user
      MARIADB_DATABASE: app
    volumes:
      - ./db/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - target: 3306 # ゲスト は 3306 にマッピングする
        published: 13306 # ホスト to ゲスト は 13306 から入る
        protocol: tcp
        mode: host
    restart: always
    expose:
      - "3306"
